#Russian Mad Lib
print("Enter a name:")
name = input()
print("Enter a country:")
country = input()
print("Enter a sport:")
sport = input()
print("Enter a superhero:")
superhero = input()
print()
print("Once upon a time a Russian named " + name + " was born.")
print("The Russian fought all the bears in the forest.")
print(name + " travelled to " + country + " once.")
print("Now they have renamed that " + country + " to " + name + "-land.")
print("The national sport there is: " + sport + ".")
print("The only non-Russian in " + name + "-land is " + superhero + ".")
print("Now GTFO!")
print(" :) The end ")
